# This file was auto-generated by Fern from our API Definition.

import typing

AiGenerationStatus = typing.Union[
    typing.Literal["PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"], typing.Any
]
