# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error_response_data import ErrorResponseData


class ErrorResponse(UniversalBaseModel):
    """
    Error envelope. The machine-readable `code` and HTTP `status` are always present; the human-readable reason is in `message` / `data.message`.
    """

    code: str = pydantic.Field()
    """
    e.g. "BAD_REQUEST", "UNAUTHORIZED", "NOT_FOUND".
    """

    status: int
    message: typing.Optional[str] = None
    defined: typing.Optional[bool] = None
    data: typing.Optional[ErrorResponseData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
