# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ErrorResponseData(UniversalBaseModel):
    message: typing.Optional[str] = None
    user_message: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="userMessage"),
        pydantic.Field(alias="userMessage", description="End-user-safe explanation, when available."),
    ] = None
    """
    End-user-safe explanation, when available.
    """

    error_tag: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="errorTag"), pydantic.Field(alias="errorTag")
    ] = None
    is_retryable: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isRetryable"), pydantic.Field(alias="isRetryable")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
