# This file was auto-generated by Fern from our API Definition.

import typing

OauthScope = typing.Union[
    typing.Literal[
        "posts:read",
        "posts:write",
        "tags:read",
        "tags:write",
        "social-accounts:read",
        "social-accounts:write",
        "channels:read",
        "media:read",
        "media:write",
        "analytics:read",
        "org:read",
        "ai:read",
        "ai:write",
        "webhooks:read",
        "webhooks:write",
    ],
    typing.Any,
]
