# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PostPlatformConfigurationArticleTargetEntitiesItem(UniversalBaseModel):
    locales: typing.Optional[typing.List[str]] = None
    industries: typing.Optional[typing.List[str]] = None
    seniorities: typing.Optional[typing.List[str]] = None
    functions: typing.Optional[typing.List[str]] = None
    staff_count_ranges: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="staffCountRanges"),
        pydantic.Field(alias="staffCountRanges"),
    ] = None
    followed_companies: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="followedCompanies"),
        pydantic.Field(alias="followedCompanies"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
