# This file was auto-generated by Fern from our API Definition.

import typing

PostSearchApprovalStatus = typing.Union[typing.Literal["DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED"], typing.Any]
