# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .post_approval_status import PostApprovalStatus
from .post_platform_configuration import PostPlatformConfiguration
from .post_status import PostStatus


class Post(UniversalBaseModel):
    id: str
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    caption: str
    status: PostStatus
    approval_status: typing_extensions.Annotated[
        PostApprovalStatus, FieldMetadata(alias="approvalStatus"), pydantic.Field(alias="approvalStatus")
    ]
    approval_requested_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="approvalRequestedAt"),
        pydantic.Field(alias="approvalRequestedAt"),
    ] = None
    approval_requested_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="approvalRequestedBy"), pydantic.Field(alias="approvalRequestedBy")
    ] = None
    approved_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="approvedAt"), pydantic.Field(alias="approvedAt")
    ] = None
    approved_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="approvedBy"), pydantic.Field(alias="approvedBy")
    ] = None
    rejection_reason: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="rejectionReason"), pydantic.Field(alias="rejectionReason")
    ] = None
    scheduled_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="scheduledAt"), pydantic.Field(alias="scheduledAt")
    ] = None
    platform_configuration: typing_extensions.Annotated[
        typing.Optional[PostPlatformConfiguration],
        FieldMetadata(alias="platformConfiguration"),
        pydantic.Field(alias="platformConfiguration"),
    ] = None
    social_account_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="socialAccountId"), pydantic.Field(alias="socialAccountId")
    ]
    url: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
