# This file was auto-generated by Fern from our API Definition.

import typing

PostWithRelationsPlatformConfigurationFeedTargetingPlacement = typing.Union[
    typing.Literal["feed", "reels", "stories"], typing.Any
]
