# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_with_relations_platform_configuration_community_id_geo import (
    PostWithRelationsPlatformConfigurationCommunityIdGeo,
)
from .post_with_relations_platform_configuration_community_id_media_item import (
    PostWithRelationsPlatformConfigurationCommunityIdMediaItem,
)
from .post_with_relations_platform_configuration_community_id_poll import (
    PostWithRelationsPlatformConfigurationCommunityIdPoll,
)
from .post_with_relations_platform_configuration_community_id_reply_settings import (
    PostWithRelationsPlatformConfigurationCommunityIdReplySettings,
)


class PostWithRelationsPlatformConfigurationCommunityId(UniversalBaseModel):
    caption: typing.Optional[str] = None
    media: typing.Optional[typing.List[PostWithRelationsPlatformConfigurationCommunityIdMediaItem]] = None
    poll: typing.Optional[PostWithRelationsPlatformConfigurationCommunityIdPoll] = None
    community_id: typing.Optional[str] = None
    community_name: typing.Optional[str] = None
    quote_tweet_id: typing.Optional[str] = None
    in_reply_to_tweet_id: typing.Optional[str] = None
    geo: typing.Optional[PostWithRelationsPlatformConfigurationCommunityIdGeo] = None
    reply_settings: typing.Optional[PostWithRelationsPlatformConfigurationCommunityIdReplySettings] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
