# This file was auto-generated by Fern from our API Definition.

import typing

PostWithRelationsPlatformConfigurationCommunityIdReplySettings = typing.Union[
    typing.Literal["everyone", "following", "mentioned"], typing.Any
]
