# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_with_relations_platform_configuration_article_media_item_tags_item import (
    PostWithRelationsPlatformConfigurationArticleMediaItemTagsItem,
)


class PostWithRelationsPlatformConfigurationArticleMediaItem(UniversalBaseModel):
    url: str
    thumbnail_url: typing.Optional[str] = None
    thumbnail_timestamp_ms: typing.Optional[float] = None
    tags: typing.Optional[typing.List[PostWithRelationsPlatformConfigurationArticleMediaItemTagsItem]] = None
    alt: typing.Optional[str] = None
    skip_processing: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
