# This file was auto-generated by Fern from our API Definition.

import typing

PostWithRelationsPlatformConfigurationBrandedContentSponsorIdsTrialReelType = typing.Union[
    typing.Literal["manual", "auto"], typing.Any
]
