# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .post_platform_configuration_allow_embedding_license import PostPlatformConfigurationAllowEmbeddingLicense
from .post_platform_configuration_allow_embedding_media_item import PostPlatformConfigurationAllowEmbeddingMediaItem
from .post_platform_configuration_allow_embedding_visibility import PostPlatformConfigurationAllowEmbeddingVisibility


class PostPlatformConfigurationAllowEmbedding(UniversalBaseModel):
    caption: typing.Optional[str] = None
    media: typing.Optional[typing.List[PostPlatformConfigurationAllowEmbeddingMediaItem]] = None
    title: str
    category_id: typing_extensions.Annotated[str, FieldMetadata(alias="categoryId"), pydantic.Field(alias="categoryId")]
    visibility: PostPlatformConfigurationAllowEmbeddingVisibility
    license: typing.Optional[PostPlatformConfigurationAllowEmbeddingLicense] = None
    notify_subscribers: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="notifySubscribers"), pydantic.Field(alias="notifySubscribers")
    ] = None
    allow_embedding: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="allowEmbedding"), pydantic.Field(alias="allowEmbedding")
    ] = None
    made_for_kids: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="madeForKids"), pydantic.Field(alias="madeForKids")
    ] = None
    tags: typing.Optional[typing.List[str]] = None
    default_language: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="defaultLanguage"), pydantic.Field(alias="defaultLanguage")
    ] = None
    default_audio_language: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="defaultAudioLanguage"), pydantic.Field(alias="defaultAudioLanguage")
    ] = None
    recording_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="recordingDate"), pydantic.Field(alias="recordingDate")
    ] = None
    publish_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="publishAt"), pydantic.Field(alias="publishAt")
    ] = None
    contains_synthetic_media: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="containsSyntheticMedia"),
        pydantic.Field(alias="containsSyntheticMedia"),
    ] = None
    public_stats_viewable: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="publicStatsViewable"), pydantic.Field(alias="publicStatsViewable")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
