# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .image_processing_status import ImageProcessingStatus
from .social_account_disconnected_reason import SocialAccountDisconnectedReason
from .social_account_status import SocialAccountStatus
from .social_platform import SocialPlatform


class SocialAccount(UniversalBaseModel):
    id: str
    platform: SocialPlatform
    account_id: typing_extensions.Annotated[str, FieldMetadata(alias="accountId"), pydantic.Field(alias="accountId")]
    scope: str
    image_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="imageUrl"), pydantic.Field(alias="imageUrl")
    ] = None
    image_processing_status: typing_extensions.Annotated[
        ImageProcessingStatus,
        FieldMetadata(alias="imageProcessingStatus"),
        pydantic.Field(alias="imageProcessingStatus"),
    ]
    username: typing.Optional[str] = None
    platform_data: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="platformData"), pydantic.Field(alias="platformData")
    ] = None
    token_expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="tokenExpiresAt"), pydantic.Field(alias="tokenExpiresAt")
    ] = None
    user_id: typing_extensions.Annotated[str, FieldMetadata(alias="userId"), pydantic.Field(alias="userId")]
    last_refresh_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastRefreshAt"), pydantic.Field(alias="lastRefreshAt")
    ] = None
    status: SocialAccountStatus
    disconnected_reason: typing_extensions.Annotated[
        typing.Optional[SocialAccountDisconnectedReason],
        FieldMetadata(alias="disconnectedReason"),
        pydantic.Field(alias="disconnectedReason"),
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]
    refresh_token_valid: typing_extensions.Annotated[
        bool, FieldMetadata(alias="refreshTokenValid"), pydantic.Field(alias="refreshTokenValid")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
