# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ValidationErrorResponseData(UniversalBaseModel):
    form_errors: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="formErrors"), pydantic.Field(alias="formErrors")
    ] = None
    field_errors: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.List[str]]],
        FieldMetadata(alias="fieldErrors"),
        pydantic.Field(alias="fieldErrors"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
