# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .validation_error_response_data import ValidationErrorResponseData


class ValidationErrorResponse(UniversalBaseModel):
    """
    422 input validation error. `data.fieldErrors` maps each invalid field to its messages; `data.formErrors` holds errors not tied to one field.
    """

    code: str = pydantic.Field()
    """
    "INPUT_VALIDATION_FAILED"
    """

    status: int
    message: typing.Optional[str] = None
    defined: typing.Optional[bool] = None
    data: ValidationErrorResponseData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
