# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .validation_error_response_data import ValidationErrorResponseData


class ValidationErrorResponse(UniversalBaseModel):
    """
    422 error. `data.fieldErrors` maps each invalid field to its messages; `data.formErrors` holds errors not tied to one field. `code` is "INPUT_VALIDATION_FAILED" for schema validation and "UNPROCESSABLE_CONTENT" for business-rule rejections, whose reason is also in `data.message`.
    """

    code: str = pydantic.Field()
    """
    "INPUT_VALIDATION_FAILED" or "UNPROCESSABLE_CONTENT"
    """

    status: int
    message: typing.Optional[str] = None
    defined: typing.Optional[bool] = None
    data: ValidationErrorResponseData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
