# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .webhook_delivery_status import WebhookDeliveryStatus


class WebhookDelivery(UniversalBaseModel):
    id: str
    endpoint_id: typing_extensions.Annotated[str, FieldMetadata(alias="endpointId"), pydantic.Field(alias="endpointId")]
    event: str
    payload: typing.Dict[str, typing.Any]
    status: WebhookDeliveryStatus
    attempts: int
    response_status: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="responseStatus"), pydantic.Field(alias="responseStatus")
    ] = None
    last_error: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastError"), pydantic.Field(alias="lastError")
    ] = None
    delivered_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="deliveredAt"), pydantic.Field(alias="deliveredAt")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
