# This file was auto-generated by Fern from our API Definition.

import typing

WebhookEndpointEventsItem = typing.Union[
    typing.Literal["post.published", "post.failed", "generation.completed", "generation.failed"], typing.Any
]
