# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .list_platforms_response_data_item_media_rules_allowed_types_item import (
    ListPlatformsResponseDataItemMediaRulesAllowedTypesItem,
)


class ListPlatformsResponseDataItemMediaRules(UniversalBaseModel):
    min: typing.Optional[float] = None
    max: float
    allowed_types: typing_extensions.Annotated[
        typing.Optional[typing.List[ListPlatformsResponseDataItemMediaRulesAllowedTypesItem]],
        FieldMetadata(alias="allowedTypes"),
        pydantic.Field(alias="allowedTypes"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
