# This file was auto-generated by Fern from our API Definition.

import typing

ListPlatformsResponseDataItemCaptionLengthUnit = typing.Union[
    typing.Literal["characters", "graphemes", "characters_emoji_bytes"], typing.Any
]
