# This file was auto-generated by Fern from our API Definition.

import typing

ListPlatformsResponseDataItemMediaRulesAllowedTypesItem = typing.Union[
    typing.Literal["IMAGE", "VIDEO", "GIF"], typing.Any
]
