# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.media import Media
from ..types.presigned_post import PresignedPost
from .raw_client import AsyncRawMediaClient, RawMediaClient
from .types.count_by_tag_media_response import CountByTagMediaResponse
from .types.create_presigned_post_intent import CreatePresignedPostIntent
from .types.create_upload_link_media_response import CreateUploadLinkMediaResponse
from .types.delete_media_response import DeleteMediaResponse
from .types.list_media_request_tag_mode import ListMediaRequestTagMode
from .types.list_media_request_type import ListMediaRequestType
from .types.list_media_response import ListMediaResponse
from .types.set_tags_media_response import SetTagsMediaResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MediaClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMediaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMediaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMediaClient
        """
        return self._raw_client

    def create_from_url(
        self,
        *,
        url: str,
        name: typing.Optional[str] = OMIT,
        alt: typing.Optional[str] = OMIT,
        content_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Downloads a publicly reachable image or video into the media library and returns the media record. Use the returned `url` in `media[].url` when creating a post. Prefer this over the presign flow whenever your client cannot issue a raw HTTP PUT (e.g. an AI agent). The source URL must be public (no auth), http(s), and at most the post upload limit (250 MB); SVG and other active content is rejected.

        Parameters
        ----------
        url : str

        name : typing.Optional[str]

        alt : typing.Optional[str]

        content_type : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.create_from_url(
            url="url",
        )
        """
        _response = self._raw_client.create_from_url(
            url=url, name=name, alt=alt, content_type=content_type, request_options=request_options
        )
        return _response.data

    def register(
        self,
        *,
        key: str,
        name: typing.Optional[str] = OMIT,
        alt: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Adds a file you uploaded with POST /v0/media/presign (intent `post`) + HTTP PUT to the media library in place — no second copy is stored — and returns the media record. Pass the presign `key`. The object's type and size are read from storage and must be an allowed image/video/audio type within the post upload limit (250 MB). Idempotent: registering the same key again returns the existing record. Returns 404 when no uploaded object exists for the key in your workspace.

        Parameters
        ----------
        key : str
            The `key` returned by POST /v0/media/presign, after the bytes were PUT to its `url`. The stored media URL for that key is also accepted.

        name : typing.Optional[str]

        alt : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.register(
            key="key",
        )
        """
        _response = self._raw_client.register(key=key, name=name, alt=alt, request_options=request_options)
        return _response.data

    def create_upload_link(
        self, *, expires_in_hours: typing.Optional[int] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateUploadLinkMediaResponse:
        """
        Returns a short-lived URL to a page where the user uploads files from their device (or a pasted attachment) straight into the media library. Hand the URL to the user; once they've uploaded, call GET /v0/media (list media, newest first) and reference the returned `url` when creating a post. Use this whenever the file isn't already at a public URL.

        Parameters
        ----------
        expires_in_hours : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateUploadLinkMediaResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.create_upload_link()
        """
        _response = self._raw_client.create_upload_link(
            expires_in_hours=expires_in_hours, request_options=request_options
        )
        return _response.data

    def upload(
        self,
        *,
        file: core.File,
        name: typing.Optional[str] = OMIT,
        alt: typing.Optional[str] = OMIT,
        content_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Upload raw image, video, or audio bytes directly as multipart/form-data. The file is stored in your media library and the record is returned; use its `url` in `media[].url` when creating a post. When the file part's type is missing or generic (`application/octet-stream`, `text/plain`), the type is detected from the file's bytes, then its filename extension. Max 250 MB; SVG and other active content is rejected. For a file already hosted at a public URL, prefer POST /v0/media/from-url.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        name : typing.Optional[str]

        alt : typing.Optional[str]

        content_type : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.upload()
        """
        _response = self._raw_client.upload(
            file=file, name=name, alt=alt, content_type=content_type, request_options=request_options
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Media:
        """
        Retrieve media information by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        url: typing.Optional[str] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        width: typing.Optional[int] = OMIT,
        height: typing.Optional[int] = OMIT,
        size: typing.Optional[int] = OMIT,
        duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Update media information and metadata

        Parameters
        ----------
        id : str

        url : typing.Optional[str]

        mime_type : typing.Optional[str]

        width : typing.Optional[int]

        height : typing.Optional[int]

        size : typing.Optional[int]

        duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            url=url,
            mime_type=mime_type,
            width=width,
            height=height,
            size=size,
            duration=duration,
            request_options=request_options,
        )
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteMediaResponse:
        """
        Delete a media object and remove its files from storage. Fails with a conflict when the media is attached to any post — remove it from those posts (or delete them) first.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteMediaResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def list(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        q: typing.Optional[str] = None,
        type: typing.Optional[ListMediaRequestType] = None,
        tag_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        tag_mode: typing.Optional[ListMediaRequestTagMode] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMediaResponse:
        """
        List media for the organization with page pagination, search, type and tag filters

        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        q : typing.Optional[str]

        type : typing.Optional[ListMediaRequestType]

        tag_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        tag_mode : typing.Optional[ListMediaRequestTagMode]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMediaResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.list()
        """
        _response = self._raw_client.list(
            page=page, limit=limit, q=q, type=type, tag_ids=tag_ids, tag_mode=tag_mode, request_options=request_options
        )
        return _response.data

    def set_tags(
        self, media_id: str, *, tag_ids: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> SetTagsMediaResponse:
        """
        Replace the set of tags attached to a media item with the provided tag IDs

        Parameters
        ----------
        media_id : str

        tag_ids : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetTagsMediaResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.set_tags(
            media_id="mediaId",
            tag_ids=["tagIds"],
        )
        """
        _response = self._raw_client.set_tags(media_id, tag_ids=tag_ids, request_options=request_options)
        return _response.data

    def count_by_tag(self, *, request_options: typing.Optional[RequestOptions] = None) -> CountByTagMediaResponse:
        """
        Return media counts grouped by tag for the organization

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CountByTagMediaResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.count_by_tag()
        """
        _response = self._raw_client.count_by_tag(request_options=request_options)
        return _response.data

    def create_presigned_post(
        self,
        *,
        content_type: str,
        key: str,
        size: typing.Optional[int] = OMIT,
        intent: typing.Optional[CreatePresignedPostIntent] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PresignedPost:
        """
        Returns a presigned PUT URL. Upload by issuing an HTTP PUT of the raw file bytes to `url` with a `Content-Type` header matching `contentType`, then reference the returned `key` when creating a post.

        Parameters
        ----------
        content_type : str

        key : str

        size : typing.Optional[int]

        intent : typing.Optional[CreatePresignedPostIntent]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PresignedPost
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.media.create_presigned_post(
            content_type="contentType",
            key="key",
        )
        """
        _response = self._raw_client.create_presigned_post(
            content_type=content_type, key=key, size=size, intent=intent, request_options=request_options
        )
        return _response.data


class AsyncMediaClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMediaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMediaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMediaClient
        """
        return self._raw_client

    async def create_from_url(
        self,
        *,
        url: str,
        name: typing.Optional[str] = OMIT,
        alt: typing.Optional[str] = OMIT,
        content_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Downloads a publicly reachable image or video into the media library and returns the media record. Use the returned `url` in `media[].url` when creating a post. Prefer this over the presign flow whenever your client cannot issue a raw HTTP PUT (e.g. an AI agent). The source URL must be public (no auth), http(s), and at most the post upload limit (250 MB); SVG and other active content is rejected.

        Parameters
        ----------
        url : str

        name : typing.Optional[str]

        alt : typing.Optional[str]

        content_type : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.create_from_url(
                url="url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_from_url(
            url=url, name=name, alt=alt, content_type=content_type, request_options=request_options
        )
        return _response.data

    async def register(
        self,
        *,
        key: str,
        name: typing.Optional[str] = OMIT,
        alt: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Adds a file you uploaded with POST /v0/media/presign (intent `post`) + HTTP PUT to the media library in place — no second copy is stored — and returns the media record. Pass the presign `key`. The object's type and size are read from storage and must be an allowed image/video/audio type within the post upload limit (250 MB). Idempotent: registering the same key again returns the existing record. Returns 404 when no uploaded object exists for the key in your workspace.

        Parameters
        ----------
        key : str
            The `key` returned by POST /v0/media/presign, after the bytes were PUT to its `url`. The stored media URL for that key is also accepted.

        name : typing.Optional[str]

        alt : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.register(
                key="key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register(key=key, name=name, alt=alt, request_options=request_options)
        return _response.data

    async def create_upload_link(
        self, *, expires_in_hours: typing.Optional[int] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateUploadLinkMediaResponse:
        """
        Returns a short-lived URL to a page where the user uploads files from their device (or a pasted attachment) straight into the media library. Hand the URL to the user; once they've uploaded, call GET /v0/media (list media, newest first) and reference the returned `url` when creating a post. Use this whenever the file isn't already at a public URL.

        Parameters
        ----------
        expires_in_hours : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateUploadLinkMediaResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.create_upload_link()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_upload_link(
            expires_in_hours=expires_in_hours, request_options=request_options
        )
        return _response.data

    async def upload(
        self,
        *,
        file: core.File,
        name: typing.Optional[str] = OMIT,
        alt: typing.Optional[str] = OMIT,
        content_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Upload raw image, video, or audio bytes directly as multipart/form-data. The file is stored in your media library and the record is returned; use its `url` in `media[].url` when creating a post. When the file part's type is missing or generic (`application/octet-stream`, `text/plain`), the type is detected from the file's bytes, then its filename extension. Max 250 MB; SVG and other active content is rejected. For a file already hosted at a public URL, prefer POST /v0/media/from-url.

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        name : typing.Optional[str]

        alt : typing.Optional[str]

        content_type : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.upload()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload(
            file=file, name=name, alt=alt, content_type=content_type, request_options=request_options
        )
        return _response.data

    async def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Media:
        """
        Retrieve media information by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        url: typing.Optional[str] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        width: typing.Optional[int] = OMIT,
        height: typing.Optional[int] = OMIT,
        size: typing.Optional[int] = OMIT,
        duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Media:
        """
        Update media information and metadata

        Parameters
        ----------
        id : str

        url : typing.Optional[str]

        mime_type : typing.Optional[str]

        width : typing.Optional[int]

        height : typing.Optional[int]

        size : typing.Optional[int]

        duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Media
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            url=url,
            mime_type=mime_type,
            width=width,
            height=height,
            size=size,
            duration=duration,
            request_options=request_options,
        )
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteMediaResponse:
        """
        Delete a media object and remove its files from storage. Fails with a conflict when the media is attached to any post — remove it from those posts (or delete them) first.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteMediaResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def list(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        q: typing.Optional[str] = None,
        type: typing.Optional[ListMediaRequestType] = None,
        tag_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        tag_mode: typing.Optional[ListMediaRequestTagMode] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMediaResponse:
        """
        List media for the organization with page pagination, search, type and tag filters

        Parameters
        ----------
        page : typing.Optional[int]

        limit : typing.Optional[int]

        q : typing.Optional[str]

        type : typing.Optional[ListMediaRequestType]

        tag_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        tag_mode : typing.Optional[ListMediaRequestTagMode]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMediaResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            page=page, limit=limit, q=q, type=type, tag_ids=tag_ids, tag_mode=tag_mode, request_options=request_options
        )
        return _response.data

    async def set_tags(
        self, media_id: str, *, tag_ids: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> SetTagsMediaResponse:
        """
        Replace the set of tags attached to a media item with the provided tag IDs

        Parameters
        ----------
        media_id : str

        tag_ids : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetTagsMediaResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.set_tags(
                media_id="mediaId",
                tag_ids=["tagIds"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_tags(media_id, tag_ids=tag_ids, request_options=request_options)
        return _response.data

    async def count_by_tag(self, *, request_options: typing.Optional[RequestOptions] = None) -> CountByTagMediaResponse:
        """
        Return media counts grouped by tag for the organization

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CountByTagMediaResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.count_by_tag()


        asyncio.run(main())
        """
        _response = await self._raw_client.count_by_tag(request_options=request_options)
        return _response.data

    async def create_presigned_post(
        self,
        *,
        content_type: str,
        key: str,
        size: typing.Optional[int] = OMIT,
        intent: typing.Optional[CreatePresignedPostIntent] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PresignedPost:
        """
        Returns a presigned PUT URL. Upload by issuing an HTTP PUT of the raw file bytes to `url` with a `Content-Type` header matching `contentType`, then reference the returned `key` when creating a post.

        Parameters
        ----------
        content_type : str

        key : str

        size : typing.Optional[int]

        intent : typing.Optional[CreatePresignedPostIntent]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PresignedPost
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.media.create_presigned_post(
                content_type="contentType",
                key="key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_presigned_post(
            content_type=content_type, key=key, size=size, intent=intent, request_options=request_options
        )
        return _response.data
