# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_whop_forums_social_accounts_response_items_item import ListWhopForumsSocialAccountsResponseItemsItem


class ListWhopForumsSocialAccountsResponse(UniversalBaseModel):
    items: typing.List[ListWhopForumsSocialAccountsResponseItemsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
