# This file was auto-generated by Fern from our API Definition.

import typing

PinterestBoardsSocialAccountsResponseDataItemPrivacy = typing.Union[
    typing.Literal["PUBLIC", "PROTECTED", "SECRET"], typing.Any
]
