# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSocialAccountsClient, RawSocialAccountsClient
from .types.delete_social_accounts_response import DeleteSocialAccountsResponse
from .types.list_social_accounts_response_item import ListSocialAccountsResponseItem
from .types.refresh_profile_social_accounts_response import RefreshProfileSocialAccountsResponse
from .types.update_social_accounts_request_image_processing_status import (
    UpdateSocialAccountsRequestImageProcessingStatus,
)
from .types.update_social_accounts_request_platform import UpdateSocialAccountsRequestPlatform
from .types.update_social_accounts_request_status import UpdateSocialAccountsRequestStatus
from .types.update_social_accounts_response import UpdateSocialAccountsResponse
from .types.update_timezone_social_accounts_response import UpdateTimezoneSocialAccountsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SocialAccountsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSocialAccountsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSocialAccountsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSocialAccountsClient
        """
        return self._raw_client

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListSocialAccountsResponseItem]:
        """
        Retrieve all connected social media accounts for the authenticated user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListSocialAccountsResponseItem]
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.social_accounts.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        platform: typing.Optional[UpdateSocialAccountsRequestPlatform] = OMIT,
        access_token: typing.Optional[str] = OMIT,
        secret_access_token: typing.Optional[str] = OMIT,
        refresh_token: typing.Optional[str] = OMIT,
        refresh_token_valid: typing.Optional[bool] = OMIT,
        token_expires_at: typing.Optional[dt.datetime] = OMIT,
        image_url: typing.Optional[str] = OMIT,
        image_processing_status: typing.Optional[UpdateSocialAccountsRequestImageProcessingStatus] = OMIT,
        platform_data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        last_refresh_at: typing.Optional[dt.datetime] = OMIT,
        status: typing.Optional[UpdateSocialAccountsRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateSocialAccountsResponse:
        """
        Update social media account settings and information

        Parameters
        ----------
        id : str

        platform : typing.Optional[UpdateSocialAccountsRequestPlatform]

        access_token : typing.Optional[str]

        secret_access_token : typing.Optional[str]

        refresh_token : typing.Optional[str]

        refresh_token_valid : typing.Optional[bool]

        token_expires_at : typing.Optional[dt.datetime]

        image_url : typing.Optional[str]

        image_processing_status : typing.Optional[UpdateSocialAccountsRequestImageProcessingStatus]

        platform_data : typing.Optional[typing.Dict[str, typing.Any]]

        last_refresh_at : typing.Optional[dt.datetime]

        status : typing.Optional[UpdateSocialAccountsRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateSocialAccountsResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.social_accounts.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            platform=platform,
            access_token=access_token,
            secret_access_token=secret_access_token,
            refresh_token=refresh_token,
            refresh_token_valid=refresh_token_valid,
            token_expires_at=token_expires_at,
            image_url=image_url,
            image_processing_status=image_processing_status,
            platform_data=platform_data,
            last_refresh_at=last_refresh_at,
            status=status,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteSocialAccountsResponse:
        """
        Remove a connected social media account

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteSocialAccountsResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.social_accounts.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update_timezone(
        self, id: str, *, timezone: str, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateTimezoneSocialAccountsResponse:
        """
        Set the IANA timezone (e.g. 'America/Los_Angeles') used to interpret queue times for this account.

        Parameters
        ----------
        id : str

        timezone : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTimezoneSocialAccountsResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.social_accounts.update_timezone(
            id="id",
            timezone="timezone",
        )
        """
        _response = self._raw_client.update_timezone(id, timezone=timezone, request_options=request_options)
        return _response.data

    def refresh_profile(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RefreshProfileSocialAccountsResponse:
        """
        Fetch the latest profile information from the connected platform and update the social account

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefreshProfileSocialAccountsResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.social_accounts.refresh_profile(
            id="id",
        )
        """
        _response = self._raw_client.refresh_profile(id, request_options=request_options)
        return _response.data


class AsyncSocialAccountsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSocialAccountsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSocialAccountsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSocialAccountsClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListSocialAccountsResponseItem]:
        """
        Retrieve all connected social media accounts for the authenticated user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListSocialAccountsResponseItem]
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_accounts.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        platform: typing.Optional[UpdateSocialAccountsRequestPlatform] = OMIT,
        access_token: typing.Optional[str] = OMIT,
        secret_access_token: typing.Optional[str] = OMIT,
        refresh_token: typing.Optional[str] = OMIT,
        refresh_token_valid: typing.Optional[bool] = OMIT,
        token_expires_at: typing.Optional[dt.datetime] = OMIT,
        image_url: typing.Optional[str] = OMIT,
        image_processing_status: typing.Optional[UpdateSocialAccountsRequestImageProcessingStatus] = OMIT,
        platform_data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        last_refresh_at: typing.Optional[dt.datetime] = OMIT,
        status: typing.Optional[UpdateSocialAccountsRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateSocialAccountsResponse:
        """
        Update social media account settings and information

        Parameters
        ----------
        id : str

        platform : typing.Optional[UpdateSocialAccountsRequestPlatform]

        access_token : typing.Optional[str]

        secret_access_token : typing.Optional[str]

        refresh_token : typing.Optional[str]

        refresh_token_valid : typing.Optional[bool]

        token_expires_at : typing.Optional[dt.datetime]

        image_url : typing.Optional[str]

        image_processing_status : typing.Optional[UpdateSocialAccountsRequestImageProcessingStatus]

        platform_data : typing.Optional[typing.Dict[str, typing.Any]]

        last_refresh_at : typing.Optional[dt.datetime]

        status : typing.Optional[UpdateSocialAccountsRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateSocialAccountsResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_accounts.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            platform=platform,
            access_token=access_token,
            secret_access_token=secret_access_token,
            refresh_token=refresh_token,
            refresh_token_valid=refresh_token_valid,
            token_expires_at=token_expires_at,
            image_url=image_url,
            image_processing_status=image_processing_status,
            platform_data=platform_data,
            last_refresh_at=last_refresh_at,
            status=status,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteSocialAccountsResponse:
        """
        Remove a connected social media account

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteSocialAccountsResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_accounts.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update_timezone(
        self, id: str, *, timezone: str, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateTimezoneSocialAccountsResponse:
        """
        Set the IANA timezone (e.g. 'America/Los_Angeles') used to interpret queue times for this account.

        Parameters
        ----------
        id : str

        timezone : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTimezoneSocialAccountsResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_accounts.update_timezone(
                id="id",
                timezone="timezone",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_timezone(id, timezone=timezone, request_options=request_options)
        return _response.data

    async def refresh_profile(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RefreshProfileSocialAccountsResponse:
        """
        Fetch the latest profile information from the connected platform and update the social account

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefreshProfileSocialAccountsResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_accounts.refresh_profile(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.refresh_profile(id, request_options=request_options)
        return _response.data
