# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.ai_generation import AiGeneration
from .raw_client import AsyncRawAiClient, RawAiClient
from .types.generate_image_ai_request_model_key import GenerateImageAiRequestModelKey
from .types.generate_image_ai_response import GenerateImageAiResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AiClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAiClient
        """
        return self._raw_client

    def generate_image(
        self,
        *,
        prompt: str,
        model_key: typing.Optional[GenerateImageAiRequestModelKey] = OMIT,
        width: typing.Optional[int] = OMIT,
        height: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenerateImageAiResponse:
        """
        Submit an AI image generation job

        Parameters
        ----------
        prompt : str

        model_key : typing.Optional[GenerateImageAiRequestModelKey]

        width : typing.Optional[int]

        height : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenerateImageAiResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.ai.generate_image(
            prompt="prompt",
        )
        """
        _response = self._raw_client.generate_image(
            prompt=prompt, model_key=model_key, width=width, height=height, request_options=request_options
        )
        return _response.data

    def get_generation(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> AiGeneration:
        """
        Get the status and details of a generation job

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AiGeneration
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.ai.get_generation(
            id="id",
        )
        """
        _response = self._raw_client.get_generation(id=id, request_options=request_options)
        return _response.data


class AsyncAiClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAiClient
        """
        return self._raw_client

    async def generate_image(
        self,
        *,
        prompt: str,
        model_key: typing.Optional[GenerateImageAiRequestModelKey] = OMIT,
        width: typing.Optional[int] = OMIT,
        height: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenerateImageAiResponse:
        """
        Submit an AI image generation job

        Parameters
        ----------
        prompt : str

        model_key : typing.Optional[GenerateImageAiRequestModelKey]

        width : typing.Optional[int]

        height : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenerateImageAiResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.ai.generate_image(
                prompt="prompt",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.generate_image(
            prompt=prompt, model_key=model_key, width=width, height=height, request_options=request_options
        )
        return _response.data

    async def get_generation(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> AiGeneration:
        """
        Get the status and details of a generation job

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AiGeneration
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.ai.get_generation(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_generation(id=id, request_options=request_options)
        return _response.data
