# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.rate_limit_error_response import RateLimitErrorResponse


class TooManyRequestsError(ApiError):
    def __init__(self, body: RateLimitErrorResponse, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=429, headers=headers, body=body)
