# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .analytics_series_posts_response import AnalyticsSeriesPostsResponse
    from .analytics_series_posts_response_data_item import AnalyticsSeriesPostsResponseDataItem
    from .analytics_summary_posts_response import AnalyticsSummaryPostsResponse
    from .create_posts_response import CreatePostsResponse
    from .create_posts_response_media_item import CreatePostsResponseMediaItem
    from .create_posts_response_media_item_tags_item import CreatePostsResponseMediaItemTagsItem
    from .create_posts_response_media_item_tags_item_platform import CreatePostsResponseMediaItemTagsItemPlatform
    from .create_posts_response_media_item_tags_item_type import CreatePostsResponseMediaItemTagsItemType
    from .list_posts_request_approval_status import ListPostsRequestApprovalStatus
    from .list_posts_request_status import ListPostsRequestStatus
    from .list_posts_request_statuses_item import ListPostsRequestStatusesItem
    from .list_posts_request_tag_mode import ListPostsRequestTagMode
    from .list_posts_response import ListPostsResponse
    from .post_create_action import PostCreateAction
    from .post_create_media_item import PostCreateMediaItem
    from .post_create_media_item_tags_item import PostCreateMediaItemTagsItem
    from .post_create_media_item_tags_item_platform import PostCreateMediaItemTagsItemPlatform
    from .post_create_media_item_tags_item_type import PostCreateMediaItemTagsItemType
    from .post_create_parts_item import PostCreatePartsItem
    from .post_create_parts_item_media_item import PostCreatePartsItemMediaItem
    from .post_create_parts_item_media_item_tags_item import PostCreatePartsItemMediaItemTagsItem
    from .post_create_parts_item_media_item_tags_item_platform import PostCreatePartsItemMediaItemTagsItemPlatform
    from .post_create_parts_item_media_item_tags_item_type import PostCreatePartsItemMediaItemTagsItemType
    from .post_create_thumbnail import PostCreateThumbnail
    from .post_create_thumbnail_tags_item import PostCreateThumbnailTagsItem
    from .post_create_thumbnail_tags_item_platform import PostCreateThumbnailTagsItemPlatform
    from .post_create_thumbnail_tags_item_type import PostCreateThumbnailTagsItemType
    from .update_posts_request_media_item import UpdatePostsRequestMediaItem
    from .update_posts_request_status import UpdatePostsRequestStatus
_dynamic_imports: typing.Dict[str, str] = {
    "AnalyticsSeriesPostsResponse": ".analytics_series_posts_response",
    "AnalyticsSeriesPostsResponseDataItem": ".analytics_series_posts_response_data_item",
    "AnalyticsSummaryPostsResponse": ".analytics_summary_posts_response",
    "CreatePostsResponse": ".create_posts_response",
    "CreatePostsResponseMediaItem": ".create_posts_response_media_item",
    "CreatePostsResponseMediaItemTagsItem": ".create_posts_response_media_item_tags_item",
    "CreatePostsResponseMediaItemTagsItemPlatform": ".create_posts_response_media_item_tags_item_platform",
    "CreatePostsResponseMediaItemTagsItemType": ".create_posts_response_media_item_tags_item_type",
    "ListPostsRequestApprovalStatus": ".list_posts_request_approval_status",
    "ListPostsRequestStatus": ".list_posts_request_status",
    "ListPostsRequestStatusesItem": ".list_posts_request_statuses_item",
    "ListPostsRequestTagMode": ".list_posts_request_tag_mode",
    "ListPostsResponse": ".list_posts_response",
    "PostCreateAction": ".post_create_action",
    "PostCreateMediaItem": ".post_create_media_item",
    "PostCreateMediaItemTagsItem": ".post_create_media_item_tags_item",
    "PostCreateMediaItemTagsItemPlatform": ".post_create_media_item_tags_item_platform",
    "PostCreateMediaItemTagsItemType": ".post_create_media_item_tags_item_type",
    "PostCreatePartsItem": ".post_create_parts_item",
    "PostCreatePartsItemMediaItem": ".post_create_parts_item_media_item",
    "PostCreatePartsItemMediaItemTagsItem": ".post_create_parts_item_media_item_tags_item",
    "PostCreatePartsItemMediaItemTagsItemPlatform": ".post_create_parts_item_media_item_tags_item_platform",
    "PostCreatePartsItemMediaItemTagsItemType": ".post_create_parts_item_media_item_tags_item_type",
    "PostCreateThumbnail": ".post_create_thumbnail",
    "PostCreateThumbnailTagsItem": ".post_create_thumbnail_tags_item",
    "PostCreateThumbnailTagsItemPlatform": ".post_create_thumbnail_tags_item_platform",
    "PostCreateThumbnailTagsItemType": ".post_create_thumbnail_tags_item_type",
    "UpdatePostsRequestMediaItem": ".update_posts_request_media_item",
    "UpdatePostsRequestStatus": ".update_posts_request_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AnalyticsSeriesPostsResponse",
    "AnalyticsSeriesPostsResponseDataItem",
    "AnalyticsSummaryPostsResponse",
    "CreatePostsResponse",
    "CreatePostsResponseMediaItem",
    "CreatePostsResponseMediaItemTagsItem",
    "CreatePostsResponseMediaItemTagsItemPlatform",
    "CreatePostsResponseMediaItemTagsItemType",
    "ListPostsRequestApprovalStatus",
    "ListPostsRequestStatus",
    "ListPostsRequestStatusesItem",
    "ListPostsRequestTagMode",
    "ListPostsResponse",
    "PostCreateAction",
    "PostCreateMediaItem",
    "PostCreateMediaItemTagsItem",
    "PostCreateMediaItemTagsItemPlatform",
    "PostCreateMediaItemTagsItemType",
    "PostCreatePartsItem",
    "PostCreatePartsItemMediaItem",
    "PostCreatePartsItemMediaItemTagsItem",
    "PostCreatePartsItemMediaItemTagsItemPlatform",
    "PostCreatePartsItemMediaItemTagsItemType",
    "PostCreateThumbnail",
    "PostCreateThumbnailTagsItem",
    "PostCreateThumbnailTagsItemPlatform",
    "PostCreateThumbnailTagsItemType",
    "UpdatePostsRequestMediaItem",
    "UpdatePostsRequestStatus",
]
