# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_posts_response_platform_configuration_article_poll_duration import (
    CreatePostsResponsePlatformConfigurationArticlePollDuration,
)


class CreatePostsResponsePlatformConfigurationArticlePoll(UniversalBaseModel):
    question: str
    options: typing.List[str]
    duration: typing.Optional[CreatePostsResponsePlatformConfigurationArticlePollDuration] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
