# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_posts_response_platform_configuration_feed_targeting_media_item import (
    CreatePostsResponsePlatformConfigurationFeedTargetingMediaItem,
)
from .create_posts_response_platform_configuration_feed_targeting_placement import (
    CreatePostsResponsePlatformConfigurationFeedTargetingPlacement,
)


class CreatePostsResponsePlatformConfigurationFeedTargeting(UniversalBaseModel):
    caption: typing.Optional[str] = None
    media: typing.Optional[typing.List[CreatePostsResponsePlatformConfigurationFeedTargetingMediaItem]] = None
    placement: typing.Optional[CreatePostsResponsePlatformConfigurationFeedTargetingPlacement] = None
    location: typing.Optional[str] = None
    collaborators: typing.Optional[typing.List[str]] = None
    first_comment: typing.Optional[str] = None
    tagged_users: typing.Optional[typing.List[str]] = None
    scheduled_publish_time: typing.Optional[int] = None
    feed_targeting: typing.Optional[typing.Dict[str, typing.Any]] = None
    targeting: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
