# This file was auto-generated by Fern from our API Definition.

import typing

CreatePostsResponsePlatformConfigurationAllowEmbeddingMediaItemTagsItemPlatform = typing.Union[
    typing.Literal[
        "bluesky", "facebook", "instagram", "linkedin", "pinterest", "threads", "tiktok", "twitter", "youtube"
    ],
    typing.Any,
]
