# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_posts_response_platform_configuration_allowlisted_country_codes_gif_gif_provider import (
    CreatePostsResponsePlatformConfigurationAllowlistedCountryCodesGifGifProvider,
)


class CreatePostsResponsePlatformConfigurationAllowlistedCountryCodesGif(UniversalBaseModel):
    gif_id: str
    gif_provider: typing.Optional[CreatePostsResponsePlatformConfigurationAllowlistedCountryCodesGifGifProvider] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
