# This file was auto-generated by Fern from our API Definition.

import typing

CreatePostsResponsePlatformConfigurationAllowlistedCountryCodesGifGifProvider = typing.Union[
    typing.Literal["GIPHY"], typing.Any
]
