# This file was auto-generated by Fern from our API Definition.

import typing

CreatePostsResponsePlatformConfigurationAllowEmbeddingMediaItemTagsItemType = typing.Union[
    typing.Literal["user", "business"], typing.Any
]
