# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_posts_response_platform_configuration_branded_content_sponsor_ids_media_item import (
    CreatePostsResponsePlatformConfigurationBrandedContentSponsorIdsMediaItem,
)
from .create_posts_response_platform_configuration_branded_content_sponsor_ids_placement import (
    CreatePostsResponsePlatformConfigurationBrandedContentSponsorIdsPlacement,
)
from .create_posts_response_platform_configuration_branded_content_sponsor_ids_trial_reel_type import (
    CreatePostsResponsePlatformConfigurationBrandedContentSponsorIdsTrialReelType,
)


class CreatePostsResponsePlatformConfigurationBrandedContentSponsorIds(UniversalBaseModel):
    caption: typing.Optional[str] = None
    media: typing.Optional[typing.List[CreatePostsResponsePlatformConfigurationBrandedContentSponsorIdsMediaItem]] = (
        None
    )
    placement: typing.Optional[CreatePostsResponsePlatformConfigurationBrandedContentSponsorIdsPlacement] = None
    collaborators: typing.Optional[typing.List[str]] = None
    share_to_feed: typing.Optional[bool] = None
    location: typing.Optional[str] = None
    trial_reel_type: typing.Optional[CreatePostsResponsePlatformConfigurationBrandedContentSponsorIdsTrialReelType] = (
        None
    )
    music: typing.Optional[str] = None
    tagged_products: typing.Optional[str] = None
    first_comment: typing.Optional[str] = None
    notify_me: typing.Optional[bool] = None
    is_paid_partnership: typing.Optional[bool] = None
    branded_content_sponsor_ids: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
