# This file was auto-generated by Fern from our API Definition.

import typing

CreatePostsResponsePlatformConfigurationArticleAuthorKind = typing.Union[
    typing.Literal["person", "organization"], typing.Any
]
