# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_posts_response_platform_configuration_external_media_item_tags_item_platform import (
    CreatePostsResponsePlatformConfigurationExternalMediaItemTagsItemPlatform,
)
from .create_posts_response_platform_configuration_external_media_item_tags_item_type import (
    CreatePostsResponsePlatformConfigurationExternalMediaItemTagsItemType,
)


class CreatePostsResponsePlatformConfigurationExternalMediaItemTagsItem(UniversalBaseModel):
    id: str
    type: CreatePostsResponsePlatformConfigurationExternalMediaItemTagsItemType
    platform: CreatePostsResponsePlatformConfigurationExternalMediaItemTagsItemPlatform
    x: typing.Optional[float] = None
    y: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
