# This file was auto-generated by Fern from our API Definition.

import typing

CreatePostsResponsePlatformConfigurationArticlePollDuration = typing.Union[
    typing.Literal["ONE_DAY", "THREE_DAYS", "SEVEN_DAYS", "FOURTEEN_DAYS"], typing.Any
]
