# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.post_status import PostStatus
from ...types.social_account_public import SocialAccountPublic
from .create_posts_response_media_item import CreatePostsResponseMediaItem
from .create_posts_response_platform_configuration import CreatePostsResponsePlatformConfiguration


class CreatePostsResponse(UniversalBaseModel):
    id: str
    external_id: typing.Optional[str] = None
    caption: str
    status: PostStatus
    scheduled_at: typing.Optional[dt.datetime] = None
    platform_configuration: typing.Optional[CreatePostsResponsePlatformConfiguration] = None
    media: typing.List[CreatePostsResponseMediaItem]
    social_accounts: typing.List[SocialAccountPublic]
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
