# This file was auto-generated by Fern from our API Definition.

import typing

ListPostsRequestApprovalStatus = typing.Union[
    typing.Literal["DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED"], typing.Any
]
