# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.post_with_relations import PostWithRelations


class ListPostsResponse(UniversalBaseModel):
    posts: typing.List[PostWithRelations]
    page: float
    total_pages: typing_extensions.Annotated[
        float, FieldMetadata(alias="totalPages"), pydantic.Field(alias="totalPages")
    ]
    total: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
