# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_create_media_item_tags_item_platform import PostCreateMediaItemTagsItemPlatform
from .post_create_media_item_tags_item_type import PostCreateMediaItemTagsItemType


class PostCreateMediaItemTagsItem(UniversalBaseModel):
    id: str
    type: PostCreateMediaItemTagsItemType
    platform: PostCreateMediaItemTagsItemPlatform
    x: typing.Optional[float] = None
    y: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
