# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class UpdatePostsRequestMediaItem(UniversalBaseModel):
    id: typing.Optional[str] = None
    url: typing.Optional[str] = None
    name: typing.Optional[str] = None
    mime_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="mimeType"), pydantic.Field(alias="mimeType")
    ] = None
    width: typing.Optional[float] = None
    height: typing.Optional[float] = None
    size: typing.Optional[float] = None
    duration: typing.Optional[float] = None
    alt: typing.Optional[str] = None
    bucket: typing.Optional[str] = None
    key: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
