# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.tag import Tag
from .raw_client import AsyncRawTagsClient, RawTagsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TagsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTagsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTagsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTagsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        q: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[Tag]:
        """
        Retrieve a list of tags for the authenticated user with optional search filtering

        Parameters
        ----------
        q : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Tag]
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.tags.list()
        """
        _response = self._raw_client.list(q=q, limit=limit, request_options=request_options)
        return _response.data

    def create(self, *, name: str, color: str, request_options: typing.Optional[RequestOptions] = None) -> Tag:
        """
        Create a new tag. Users can have up to 5 tags.

        Parameters
        ----------
        name : str

        color : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Tag
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.tags.create(
            name="name",
            color="color",
        )
        """
        _response = self._raw_client.create(name=name, color=color, request_options=request_options)
        return _response.data

    def update(self, id: str, *, name: str, color: str, request_options: typing.Optional[RequestOptions] = None) -> Tag:
        """
        Update an existing tag by its ID. Only the tag owner can update their tags.

        Parameters
        ----------
        id : str

        name : str

        color : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Tag
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.tags.update(
            id="id",
            name="name",
            color="color",
        )
        """
        _response = self._raw_client.update(id, name=name, color=color, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Tag:
        """
        Delete a tag by its ID. Only the tag owner can delete their tags.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Tag
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.tags.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data


class AsyncTagsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTagsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTagsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTagsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        q: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[Tag]:
        """
        Retrieve a list of tags for the authenticated user with optional search filtering

        Parameters
        ----------
        q : typing.Optional[str]

        limit : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Tag]
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tags.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(q=q, limit=limit, request_options=request_options)
        return _response.data

    async def create(self, *, name: str, color: str, request_options: typing.Optional[RequestOptions] = None) -> Tag:
        """
        Create a new tag. Users can have up to 5 tags.

        Parameters
        ----------
        name : str

        color : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Tag
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tags.create(
                name="name",
                color="color",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(name=name, color=color, request_options=request_options)
        return _response.data

    async def update(
        self, id: str, *, name: str, color: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Tag:
        """
        Update an existing tag by its ID. Only the tag owner can update their tags.

        Parameters
        ----------
        id : str

        name : str

        color : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Tag
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tags.update(
                id="id",
                name="name",
                color="color",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(id, name=name, color=color, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Tag:
        """
        Delete a tag by its ID. Only the tag owner can delete their tags.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Tag
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tags.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data
