# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.webhook_endpoint import WebhookEndpoint
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient
from .types.create_webhooks_request_events_item import CreateWebhooksRequestEventsItem
from .types.delete_webhooks_response import DeleteWebhooksResponse
from .types.list_deliveries_webhooks_response import ListDeliveriesWebhooksResponse
from .types.list_webhooks_response import ListWebhooksResponse
from .types.test_webhooks_response import TestWebhooksResponse
from .types.update_webhooks_request_events_item import UpdateWebhooksRequestEventsItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListWebhooksResponse:
        """
        List the organization's webhook endpoints. Signing secrets are masked.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        url: str,
        events: typing.Sequence[CreateWebhooksRequestEventsItem],
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Register an HTTPS endpoint for event deliveries. The response includes the signing secret ONCE — store it; later reads return a masked value.

        Parameters
        ----------
        url : str

        events : typing.Sequence[CreateWebhooksRequestEventsItem]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.create(
            url="url",
            events=["post.published"],
        )
        """
        _response = self._raw_client.create(
            url=url, events=events, description=description, request_options=request_options
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WebhookEndpoint:
        """
        Retrieve one webhook endpoint, including failure counters. The signing secret is masked.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteWebhooksResponse:
        """
        Delete a webhook endpoint and its delivery history. Deliveries already in flight are dropped.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteWebhooksResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        url: typing.Optional[str] = OMIT,
        events: typing.Optional[typing.Sequence[UpdateWebhooksRequestEventsItem]] = OMIT,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Update URL, subscribed events, description, or enabled state. Re-enabling resets the failure streak.

        Parameters
        ----------
        id : str

        url : typing.Optional[str]

        events : typing.Optional[typing.Sequence[UpdateWebhooksRequestEventsItem]]

        description : typing.Optional[str]

        enabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id, url=url, events=events, description=description, enabled=enabled, request_options=request_options
        )
        return _response.data

    def rotate_secret(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WebhookEndpoint:
        """
        Generate a new signing secret for the endpoint and return it ONCE. The old secret stops signing immediately.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.rotate_secret(
            id="id",
        )
        """
        _response = self._raw_client.rotate_secret(id, request_options=request_options)
        return _response.data

    def test(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TestWebhooksResponse:
        """
        Send a signed `ping` event to the endpoint URL and record it in the delivery history.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestWebhooksResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.test(
            id="id",
        )
        """
        _response = self._raw_client.test(id, request_options=request_options)
        return _response.data

    def list_deliveries(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListDeliveriesWebhooksResponse:
        """
        Delivery history for a webhook endpoint: event, status, attempts, last response code, and payload.

        Parameters
        ----------
        id : str

        limit : typing.Optional[int]

        page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListDeliveriesWebhooksResponse
            OK

        Examples
        --------
        from schedulin import Schedulin

        client = Schedulin(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list_deliveries(
            id="id",
        )
        """
        _response = self._raw_client.list_deliveries(id, limit=limit, page=page, request_options=request_options)
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListWebhooksResponse:
        """
        List the organization's webhook endpoints. Signing secrets are masked.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        url: str,
        events: typing.Sequence[CreateWebhooksRequestEventsItem],
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Register an HTTPS endpoint for event deliveries. The response includes the signing secret ONCE — store it; later reads return a masked value.

        Parameters
        ----------
        url : str

        events : typing.Sequence[CreateWebhooksRequestEventsItem]

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.create(
                url="url",
                events=["post.published"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            url=url, events=events, description=description, request_options=request_options
        )
        return _response.data

    async def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WebhookEndpoint:
        """
        Retrieve one webhook endpoint, including failure counters. The signing secret is masked.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteWebhooksResponse:
        """
        Delete a webhook endpoint and its delivery history. Deliveries already in flight are dropped.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteWebhooksResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        url: typing.Optional[str] = OMIT,
        events: typing.Optional[typing.Sequence[UpdateWebhooksRequestEventsItem]] = OMIT,
        description: typing.Optional[str] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookEndpoint:
        """
        Update URL, subscribed events, description, or enabled state. Re-enabling resets the failure streak.

        Parameters
        ----------
        id : str

        url : typing.Optional[str]

        events : typing.Optional[typing.Sequence[UpdateWebhooksRequestEventsItem]]

        description : typing.Optional[str]

        enabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id, url=url, events=events, description=description, enabled=enabled, request_options=request_options
        )
        return _response.data

    async def rotate_secret(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookEndpoint:
        """
        Generate a new signing secret for the endpoint and return it ONCE. The old secret stops signing immediately.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookEndpoint
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.rotate_secret(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_secret(id, request_options=request_options)
        return _response.data

    async def test(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TestWebhooksResponse:
        """
        Send a signed `ping` event to the endpoint URL and record it in the delivery history.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestWebhooksResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.test(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.test(id, request_options=request_options)
        return _response.data

    async def list_deliveries(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListDeliveriesWebhooksResponse:
        """
        Delivery history for a webhook endpoint: event, status, attempts, last response code, and payload.

        Parameters
        ----------
        id : str

        limit : typing.Optional[int]

        page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListDeliveriesWebhooksResponse
            OK

        Examples
        --------
        import asyncio

        from schedulin import AsyncSchedulin

        client = AsyncSchedulin(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list_deliveries(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_deliveries(id, limit=limit, page=page, request_options=request_options)
        return _response.data
